version: '3.9'

services:

  front:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - migrations
      - postgres
    ports:
      - "8000:8000"

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: sh -c "python3 manage.py migrate"

  postgres:
    image: postgres:14.8-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgres_data:
