version: '3.9'

services:

  front:
    build:
      context: ./front
      dockerfile: ./docker/Dockerfile
    volumes:
      - app_volume:/app
      - ./front/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app_volume:/app
    env_file:
      - .env
    depends_on:
      - migrations
      - postgres
    ports:
      - "8000:8000"

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app_volume:/app
    depends_on:
      - postgres
    command: sh -c "sleep 10 && python manage.py migrate"

  postgres:
    image: postgres:14.7-alpine
    container_name: todolist_pg_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
    ports:
      - "5432:5432"

volumes:
  app_volume:
  postgres_data:
