# Generated by Django 4.2.3 on 2023-07-06 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('updated', models.DateTimeField(verbose_name='Updated')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('due_date', models.DateTimeField(null=True, verbose_name='Due Date')),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'To do'), (2, 'In progress'), (3, 'Done'), (4, 'Archived')],
                        default=1,
                        verbose_name='Status',
                    ),
                ),
                (
                    'priority',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')],
                        default=2,
                        verbose_name='Priority',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='goals.goalcategory', verbose_name='Category'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
    ]
