# Generated by Django 4.2.3 on 2023-07-17 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('goals', '0007_alter_goalcategory_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardparticipant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
    ]
