# Generated by Django 4.2.3 on 2023-07-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(unique=True, verbose_name='Telegram Username'),
        ),
    ]
